### PR TITLE
ReactJS easy example added to the README

### PR DESCRIPTION
**Pull request by dolev146**
Hey 

I added my simple example in ReactJS to code sandbox to the documentation readme

I believe it is much simple than the example provided in ReactTS therefore I believe it would benefit new users

### CODE REVIEW

**Comment by dolev146** [comment]
## JavaScript Demo

To see a demo of a static line graph in MuPlot, check out the [Demo in CodeSandBox](https://codesandbox.io/s/uplot-react-example-documentation-dont-delete-wvp94u?file=/src/App.js "Demo in CodeSandBox"). This demo is created using React and uPlot library.
image

```this is what I have added```

**Comment by skalinichev** [comment]
Yeah, that may be useful for some people to have a simple example. Though the code of the example should be kept in this repository, otherwise we won't be able to track any changes there. E.g. we can replace the ClassApp example with this one (not as many people are using classes nowadays anyway)

As for JS vs TS. There is no much difference in this case either, we just need to provide types for options/data. I'm also fine with creating a separate js file for it though.

**Comment by dolev146** [comment]
So how should I name the file ? And where should I save it ? 
Do you want me to include the code also on the Readme ? 

Please let me know , what are the next steps you want me to do

**Comment by dolev146** [comment]
Me as a beginner I can't figure out how to us the typescript example in my project, therefore it really helps to have a JavaScript example Ready to use as well

**Comment by dolev146** [comment]
Do you know of any good place to learn React typescript? 
And another question, if I plan to to do my project with friends does it significantly better to learn React Typescript?

**Comment by skalinichev** [comment]
Sorry for the late reply, was a bit busy.

Regarding the questions:
1. Ideally we should create a separate directory react/examples/ and place all the examples there. Though it would require some refactoring in the build scripts. If you fill that you're up to it, please do it. Otherwise just create a file in react directory, e.g. uplot-react-simple-example.js I will do the refactoring later on.
2. About TypeScript. For me the best way to learn was to create my own small project. It helps to grasp the essence of TS much faster than watching/reading some guides/tutorials w/o trying to write anything yourself.
3. I would definitely recommend TS if you're planning to work on the same project with several people. But then again it's just me. Try both technologies and see what works best for you.

**Comment by dolev146** [comment]
1. i will try to refactor the build scripts, and update you if i was able to do so, if not will just do what you said...
2-3 . I agree it supposed to be a lot better to work as a team when the project is using TS

**Comment by dolev146** [comment]
hey whats up! sorry , for not doing what i said i will ,

sound good i will make the file uplot-react-simple.js and make a new pr

**Comment by dolev146** [comment]
ok i updated the readme and added the js simple example file , feel free to merge and thank you a lot for making this tool available in react

**Pull request merged**
